//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotasProject.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotasProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No nos gusta este enlace, la buena noticia es que puedes pedir una nueva confirmación aquí mismo, introduce tu email y solicíítala.
        /// </summary>
        public static string AccountConfirmLinkBroken {
            get {
                return ResourceManager.GetString("AccountConfirmLinkBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Algo ha ido mal en el proceso de confirmación, obtén un nuevo código introduciendo tu correo y pulsando en &quot;Reenviar confirmación&quot;.
        /// </summary>
        public static string AccountConfirmLinkFailed {
            get {
                return ResourceManager.GetString("AccountConfirmLinkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El enlace ha caducado,  la buena noticia es que puedes pedir una nueva confirmación aquí mismo, introduce tu email y solicíítala.
        /// </summary>
        public static string AccountConfirmLinkOutdated {
            get {
                return ResourceManager.GetString("AccountConfirmLinkOutdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un problema inesperado de conexión, prueba más tarde, disculpa las molestias.
        /// </summary>
        public static string AccountConfirmLinkOutofConnection {
            get {
                return ResourceManager.GetString("AccountConfirmLinkOutofConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consulta tu bandeja de entrada, se acaba de mandar otra petición de confirmación.
        /// </summary>
        public static string AccountResendEmailVerificationCode {
            get {
                return ResourceManager.GetString("AccountResendEmailVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Un error inesperado ha ocurrido actualizando tu contraseña, disculpa las molestias e inténtalo de nuevo.
        /// </summary>
        public static string AccountResetPassUpdatingError {
            get {
                return ResourceManager.GetString("AccountResetPassUpdatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enlace roto, lo sentimos.
        /// </summary>
        public static string AccountResetPasswordBadLink {
            get {
                return ResourceManager.GetString("AccountResetPasswordBadLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AES_KEY.
        /// </summary>
        public static string AES_KEY {
            get {
                return ResourceManager.GetString("AES_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CodesExpirationInterval.
        /// </summary>
        public static string CodesExpirationInterval {
            get {
                return ResourceManager.GetString("CodesExpirationInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ConfirmEmailOKFlag.
        /// </summary>
        public static string ConfirmEmailOKFlag {
            get {
                return ResourceManager.GetString("ConfirmEmailOKFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CurrentUserObject.
        /// </summary>
        public static string CurrentUserObject {
            get {
                return ResourceManager.GetString("CurrentUserObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aún no se ha recibido la confirmación de tu correo electrónico, mira en tu bandeja de entrada (incluso en spam), y si ya has probado con el último enlace de confirmación, escribe tu email y solicita reenviar la confirmación.
        /// </summary>
        public static string EmailConfirmationMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu espacio alternativo.
        /// </summary>
        public static string HomeContactDescription {
            get {
                return ResourceManager.GetString("HomeContactDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contact.
        /// </summary>
        public static string HomeContactTitle {
            get {
                return ResourceManager.GetString("HomeContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, tienes cosas que contarnos, escríbelas..
        /// </summary>
        public static string HomeIndexDescriptionOnAuth {
            get {
                return ResourceManager.GetString("HomeIndexDescriptionOnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, tienes cosas que contarnos, escríbelas. Cuenta confirmada..
        /// </summary>
        public static string HomeIndexDescriptionOnFirstAuth {
            get {
                return ResourceManager.GetString("HomeIndexDescriptionOnFirstAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido, tienes cosas que contarnos, escríbelas. Pero antes, loguéate o regístrate..
        /// </summary>
        public static string HomeIndexDescriptionUnAuth {
            get {
                return ResourceManager.GetString("HomeIndexDescriptionUnAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        public static string HomeIndexTitle {
            get {
                return ResourceManager.GetString("HomeIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chequea en tu bandeja de entrada para confirmar tu email por favor, si no lo encuentras echa un vistazo en la carpeta de spam.
        /// </summary>
        public static string InitialEmailConfirmationMessage {
            get {
                return ResourceManager.GetString("InitialEmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a _$__%___&amp;___%__$_.
        /// </summary>
        public static string KeyCacheSeparator {
            get {
                return ResourceManager.GetString("KeyCacheSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MisNotas.
        /// </summary>
        public static string MisNotas {
            get {
                return ResourceManager.GetString("MisNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        public static string NotasEditorParamOptionEdit {
            get {
                return ResourceManager.GetString("NotasEditorParamOptionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu espacio para crear notas, consultarlas y editarlas.
        /// </summary>
        public static string NotasIndexMessage {
            get {
                return ResourceManager.GetString("NotasIndexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notas.
        /// </summary>
        public static string NotasIndexTitle {
            get {
                return ResourceManager.GetString("NotasIndexTitle", resourceCulture);
            }
        }
    }
}
